# Generated by Django 2.0.2 on 2018-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proverbs',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
